.PHONY: all nmap subfinder sublist3r testssl vulners wafw00f

all: nmap subfinder sublist3r testssl vulners wafw00f

nmap:
	cd nmap && $(MAKE)

subfinder:
	cd subfinder && $(MAKE)

sublist3r:
	cd sublist3r && $(MAKE)

testssl:
	cd testssl && $(MAKE)

vulners:
	cd vulners && $(MAKE)

wafw00f:
	cd wafw00f && $(MAKE)
